apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-postgres
spec:
  serviceName: svc-postgres
  replicas: 3
  selector:
    matchLabels:
      app: sts-postgres
  template:
    metadata:
      labels:
        app: sts-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.1
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: cm-postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-postgres
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: pvc-postgres
