apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-productions
  labels:
    app: productions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productions
  template:
    metadata:
      labels:
        app: productions
    spec:
      containers:
        - name: productions
          image: gabriwl/fiap-tech-go
          imagePullPolicy: Always
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret-productions
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
               secretKeyRef:
                  name: secret-productions
                  key: DB_PASSWORD
          envFrom:
            - configMapRef:
                name: cm-productions
          ports:
            - containerPort: 8080
